version: '3.8'

services:
  wiki-go:
    container_name: wiki-go
    image: simonfong6/wiki-go:0.0.1
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
            
networks:
  default:
    name: wiki-go
